//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public string Code { get; set; }
        public string Position { get; set; }
        public string UserDecition { get; set; }
        public string WrongLoginTime { get; set; }
        public string LockTime { get; set; }
    }
}
