//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TO_QUOC_GHI_CONGEntities : DbContext
    {
        public TO_QUOC_GHI_CONGEntities()
            : base("name=TO_QUOC_GHI_CONGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<DecisionCode> DecisionCodes { get; set; }
        public virtual DbSet<DefineTypeRecord> DefineTypeRecords { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<GroupMedia> GroupMedias { get; set; }
        public virtual DbSet<GroupRecord> GroupRecords { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Object> Objects { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Record> Records { get; set; }
        public virtual DbSet<RecordUpdateHistory> RecordUpdateHistories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
    }
}
