//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public Nullable<int> RecordID { get; set; }
        public int IsReaded { get; set; }
        public int UserID { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreadedDate { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        public virtual Record Record { get; set; }
        public virtual User User { get; set; }
    }
}
